name: app 
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^16.1.0
  timezone: ^0.9.2
  image_picker: ^1.0.4  # ✅ Ajouté ici

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/img.png
    - images/heart.png
    - images/diabet.png
    - images/kidney.png
    - images/hypertention.png
    - images/skin.png
    - images/stroke.png
